### ISSUE TITLE
For Video?

### ISSUE THREAD

**Issue by osushilover** [ai-forever/Real-ESRGAN#1]
I am pleased with your work; the level of completeness is really professional!
What should I do if I want to upscale a video on colab?
I tried to place sequentially numbered images created using ffmpeg in the inputs directory, but an error occurred.
This is the traceback.

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-9146a88ac03d> in <module>()
      2 result_image_path = 'results/sr_img%4d.jpg'
      3 
----> 4 image = Image.open(path_to_image).convert('RGB')
      5 sr_image = model.predict(np.array(image))
      6 

/usr/local/lib/python3.7/dist-packages/PIL/Image.py in open(fp, mode)
   2841 
   2842     if filename:
-> 2843         fp = builtins.open(filename, "rb")
   2844         exclusive_fp = True
   2845 

FileNotFoundError: [Errno 2] No such file or directory: 'inputs/img%4d.jpg'

**Comment by boomb0om** [comment]
Hi,
This error means that python can't find `inputs/img%4d.jpg`. You should check if it's a correct path to file
