### ISSUE TITLE
RealESRGAN_x8.pth creating issue 

### ISSUE THREAD

**Issue by air55555** [ai-forever/Real-ESRGAN#5]
I tried to test RealESRGAN_x8.pth model via your colab notebook. Got an error-

RuntimeError                              Traceback (most recent call last)
[<ipython-input-6-b53c530dcfce>](https://localhost:8080/#) in <module>()
      9 
     10 model = RealESRGAN(device, scale=4)
---> 11 model.load_weights('weights/RealESRGAN_x8.pth')

1 frames
[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in load_state_dict(self, state_dict, strict)
   1496         if len(error_msgs) > 0:
   1497             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
-> 1498                                self.__class__.__name__, "\n\t".join(error_msgs)))
   1499         return _IncompatibleKeys(missing_keys, unexpected_keys)
   1500 

RuntimeError: Error(s) in loading state_dict for RRDBNet:
	Unexpected key(s) in state_dict: "conv_up3.weight", "conv_up3.bias".

**Comment by boomb0om** [comment]
Hi,
Change `scale` parameter to `8` while creating model in the line above. It should be: 
`model = RealESRGAN(device, scale=8)`

**Comment by air55555** [comment]
Closed, working with model = RealESRGAN(device, scale=8) params
