### ISSUE TITLE
How do i train this on custom dataset?

### ISSUE THREAD

**Issue by mtkgeek** [ai-forever/Real-ESRGAN#6]
Great repo. How do I train this on my own dataset? I noticed there was a similar issue raised but the link you provided there doesn't work anymore

**Comment by boomb0om** [comment]
Hi!
It seems that [xinntao](https://github.com/xinntao) moved file to other directory. So now you can find training guide [here](https://github.com/xinntao/Real-ESRGAN/blob/master/docs/Training.md#Finetune-Real-ESRGAN-on-your-own-dataset)
